<?php

declare(strict_types=1);

/*
 * This file is part of Statflow.
 *
 * (c) Tanguy Chénier <tanguychenier@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Reporting\Infrastructure\Messenger;

/**
 * Async job message carrying the id of a pending export to be generated by the
 * worker. Immutable and serialisable so Messenger can persist it on the async
 * transport.
 */
final readonly class ExportRequested
{
    public function __construct(
        public string $exportId,
    ) {
    }
}
