#!/usr/bin/env sh
# =============================================================================
# Statflow — local secret provisioning (idempotent)
#
# Generates the secrets a fresh checkout needs to boot the backend:
#   * JWT_KEY_ID      — stable key identifier published in the JWKS (ADR-0009)
#   * JWT_PRIVATE_KEY — ES256 (ECDSA P-256) signing key, PEM (PKCS#8)
#   * JWT_PUBLIC_KEY  — matching public key, PEM
#   * INSTALL_SECRET  — per-install HKDF root for cookieless identity (ADR-0008)
#
# The values are written to apps/backend/.env.local, which Symfony loads with
# precedence over the committed apps/backend/.env defaults and which the root
# .gitignore (.env.*) keeps untracked.
#
# Idempotent by design: a key is only written if it is absent. Re-running the
# script never overwrites an existing value, so it is safe in `make setup`.
#
# Runs with only the tools present in the backend image (POSIX sh + openssl).
# Invoke it through a one-shot container with the repo root mounted, e.g.:
#   docker compose run --rm --no-deps -v "$PWD:/repo" -w /repo backend \
#     sh scripts/generate-secrets.sh
# `make secrets` wires this up for you.
#
# This script is deliberately POSIX sh (the backend image's /bin/sh is dash, not
# bash), so `[ ]` is used over the bash-only `[[ ]]` (SC2292). The key_present
# helper is a pure predicate invoked in conditions; the set -e suspension inside
# it (SC2310) is exactly the intended behaviour.
# shellcheck disable=SC2292,SC2310
# =============================================================================

set -eu

# Resolve the repository root from this script's location so it works
# regardless of the working directory it is invoked from. The script lives at
# <repo>/scripts/, so its parent is the repository root. CDPATH is cleared so a
# stray value in the environment cannot redirect the `cd`.
unset CDPATH
SCRIPT_DIR=$(cd -- "$(dirname -- "$0")" && pwd)
ROOT_DIR=$(cd -- "${SCRIPT_DIR}/.." && pwd)

# Locate the backend secrets file. When the whole repo is mounted it sits under
# apps/backend/; when only the backend tree is mounted (its /app workdir), the
# file lives next to the committed .env defaults.
if [ -d "${ROOT_DIR}/apps/backend" ]; then
  ENV_FILE="${ROOT_DIR}/apps/backend/.env.local"
elif [ -f "${ROOT_DIR}/.env" ] && [ -f "${ROOT_DIR}/composer.json" ]; then
  ENV_FILE="${ROOT_DIR}/.env.local"
else
  ENV_FILE="${ROOT_DIR}/apps/backend/.env.local"
fi

KEY_ID="statflow-es256-dev"

log() {
  printf '  %s\n' "$1"
}

# Return success if KEY (e.g. JWT_PRIVATE_KEY) already has a value in ENV_FILE.
key_present() {
  [ -f "${ENV_FILE}" ] && grep -q "^$1=" "${ENV_FILE}"
}

# Append "KEY=VALUE" to ENV_FILE. Multi-line PEM bodies are wrapped by the
# caller in double quotes, which Symfony Dotenv parses as a single value.
append_kv() {
  printf '%s=%s\n' "$1" "$2" >>"${ENV_FILE}"
}

require_openssl() {
  if ! command -v openssl >/dev/null 2>&1; then
    echo "ERROR: openssl is required but was not found in PATH." >&2
    echo "       Run this script inside the backend container (it ships openssl)." >&2
    exit 1
  fi
}

main() {
  require_openssl

  if [ ! -f "${ENV_FILE}" ]; then
    log "Creating ${ENV_FILE}"
    {
      echo "# Local development secrets (gitignored)."
      echo "# Generated by scripts/generate-secrets.sh — do not commit."
    } >"${ENV_FILE}"
  fi

  generated=0

  # ── ES256 keypair (ADR-0009) ───────────────────────────────────────────────
  if key_present JWT_PRIVATE_KEY && key_present JWT_PUBLIC_KEY; then
    log "JWT keypair already present — leaving it untouched."
  else
    log "Generating ES256 (P-256) keypair…"
    private_key=$(openssl ecparam -name prime256v1 -genkey -noout \
      | openssl pkcs8 -topk8 -nocrypt)
    public_key=$(printf '%s\n' "${private_key}" | openssl ec -pubout 2>/dev/null)

    if ! key_present JWT_KEY_ID; then
      append_kv JWT_KEY_ID "${KEY_ID}"
    fi
    append_kv JWT_PRIVATE_KEY "\"${private_key}\""
    append_kv JWT_PUBLIC_KEY "\"${public_key}\""
    generated=1
  fi

  # ── INSTALL_SECRET (ADR-0008 cookieless identity root) ──────────────────────
  if key_present INSTALL_SECRET; then
    log "INSTALL_SECRET already present — leaving it untouched."
  else
    log "Generating INSTALL_SECRET…"
    install_secret=$(openssl rand -hex 32)
    append_kv INSTALL_SECRET "${install_secret}"
    generated=1
  fi

  if [ "${generated}" -eq 1 ]; then
    log "Secrets written to apps/backend/.env.local"
  else
    log "Nothing to do — all secrets already provisioned."
  fi
}

main "$@"
