#!/usr/bin/env sh
# =============================================================================
# Statflow — local secret provisioning (idempotent)
#
# Generates the secrets a fresh checkout needs to boot the backend:
#   * JWT_KEY_ID      — stable key identifier published in the JWKS (ADR-0009)
#   * JWT_PRIVATE_KEY — ES256 (ECDSA P-256) signing key, PEM (PKCS#8)
#   * JWT_PUBLIC_KEY  — matching public key, PEM
#   * INSTALL_SECRET  — per-install HKDF root for cookieless identity (ADR-0008)
#   * APP_SECRET      — framework secret (test file only; dev gets it from the
#                       root .env via compose)
#
# Two gitignored files are provisioned (root .gitignore `.env.*` keeps them
# untracked):
#   * apps/backend/.env.local       — dev runtime (loaded over .env)
#   * apps/backend/.env.test.local  — test runtime (Symfony does NOT load
#     .env.local in the test env, so the PHPUnit integration suite needs its
#     own copy of these secrets to issue/verify ES256 tokens)
#
# Idempotent by design: a key is only written if it is absent. Re-running the
# script never overwrites an existing value, so it is safe in `make setup`.
#
# Runs with only the tools present in the backend image (POSIX sh + openssl).
# Invoke it through a one-shot container with the repo root mounted, e.g.:
#   docker compose run --rm --no-deps -v "$PWD:/repo" -w /repo backend \
#     sh scripts/generate-secrets.sh
# `make secrets` wires this up for you.
#
# This script is deliberately POSIX sh (the backend image's /bin/sh is dash, not
# bash), so `[ ]` is used over the bash-only `[[ ]]` (SC2292). The key_present
# helper is a pure predicate invoked in conditions; the set -e suspension inside
# it (SC2310) is exactly the intended behaviour.
# shellcheck disable=SC2292,SC2310
# =============================================================================

set -eu

# Resolve the repository root from this script's location so it works regardless
# of the working directory it is invoked from. The script lives at <repo>/scripts/,
# so its parent is the repository root. CDPATH is cleared so a stray value in the
# environment cannot redirect the `cd`.
unset CDPATH
SCRIPT_DIR=$(cd -- "$(dirname -- "$0")" && pwd)
ROOT_DIR=$(cd -- "${SCRIPT_DIR}/.." && pwd)

# Locate the backend directory. When the whole repo is mounted it sits under
# apps/backend/; when only the backend tree is mounted (its /app workdir), the
# secrets files live next to the committed .env defaults.
if [ -d "${ROOT_DIR}/apps/backend" ]; then
  BACKEND_DIR="${ROOT_DIR}/apps/backend"
else
  BACKEND_DIR="${ROOT_DIR}"
fi

KEY_ID="statflow-es256-dev"

log() {
  printf '  %s\n' "$1"
}

require_openssl() {
  if ! command -v openssl >/dev/null 2>&1; then
    echo "ERROR: openssl is required but was not found in PATH." >&2
    echo "       Run this script inside the backend container (it ships openssl)." >&2
    exit 1
  fi
}

# Return success if KEY already has a value in FILE ($1=key, $2=file).
key_present() {
  [ -f "$2" ] && grep -q "^$1=" "$2"
}

# Provision the secrets a target env file needs. $1 = file path, $2 = "test" to
# also write APP_SECRET. Each value is written only if absent (idempotent).
provision() {
  _file="$1"
  _want_app_secret="${2:-}"

  if [ ! -f "${_file}" ]; then
    log "Creating ${_file}"
    {
      echo "# Local secrets (gitignored)."
      echo "# Generated by scripts/generate-secrets.sh — do not commit."
    } >"${_file}"
  fi

  if key_present JWT_PRIVATE_KEY "${_file}" && key_present JWT_PUBLIC_KEY "${_file}"; then
    log "JWT keypair already present in ${_file} — leaving it untouched."
  else
    log "Generating ES256 (P-256) keypair for ${_file}…"
    _private=$(openssl ecparam -name prime256v1 -genkey -noout | openssl pkcs8 -topk8 -nocrypt)
    _public=$(printf '%s\n' "${_private}" | openssl ec -pubout 2>/dev/null)
    key_present JWT_KEY_ID "${_file}" || printf 'JWT_KEY_ID=%s\n' "${KEY_ID}" >>"${_file}"
    printf 'JWT_PRIVATE_KEY="%s"\n' "${_private}" >>"${_file}"
    printf 'JWT_PUBLIC_KEY="%s"\n' "${_public}" >>"${_file}"
  fi

  if key_present INSTALL_SECRET "${_file}"; then
    log "INSTALL_SECRET already present in ${_file}."
  else
    printf 'INSTALL_SECRET=%s\n' "$(openssl rand -hex 32)" >>"${_file}"
  fi

  if [ "${_want_app_secret}" = "test" ] && ! key_present APP_SECRET "${_file}"; then
    printf 'APP_SECRET=%s\n' "$(openssl rand -hex 16)" >>"${_file}"
  fi
}

main() {
  require_openssl
  provision "${BACKEND_DIR}/.env.local"
  provision "${BACKEND_DIR}/.env.test.local" "test"
  log "Done — dev and test secrets provisioned."
}

main "$@"
